---
- name: WASM build env
  hosts: all
  roles:
    - role: emsdk
    - role: wasi-sdk
    - role: wasmtime

- name: Buildbot service
  hosts: wasm_buildbot
  roles:
    - role: staticdev.pyenv
    - role: buildbot
  post_tasks:
    - name: Show path to buildbot.tac
      ansible.builtin.debug:
        msg: "Buildbot TAC file is {{ buildbot_basedir }}/buildbot.tac"
    - name: Print systemctl command
      ansible.builtin.debug:
        msg: "systemctl start buildbot.service"

- name: Core dev test host
  hosts: wasm_coredev
  roles:
    - role: coredev
