---
- name: WASM build env
  hosts: all

  vars:
    emsdk_version: "3.1.13"
    wasi_sdk_version: "16"
    wasmtime_version: "0.36.0"
    pyenv_env: "system"
    pyenv_path: "/opt/pyenv"
    pyenv_enable_autocompletion: false
    pyenv_python_versions:
      - 3.9.13
    pyenv_global:
      - 3.9.13
    buildbot_user: "buildbot"
    buildbot_home: "/opt/buildbot"
    buildbot_name: "bcannon-wasm"

  roles:
    - role: emsdk
    - role: wasi-sdk
    - role: wasix
    - role: wasmtime
    - role: staticdev.pyenv
    - role: buildbot
