---
- name: Install distro dependencies (Debian/Ubuntu)
  package:
    state: present
    name:
      - libpq-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install distro dependencies (Fedora)
  package:
    state: present
    name:
      - libpq-devel
  when: ansible_distribution == 'Fedora'

- name: Create buildbot user account
  ansible.builtin.user:
    name: "{{ buildbot_user }}"
    comment: Python buildbot
    create_home: true
    home: "{{ buildbot_home }}"

- name: Create buildbot venv
  ansible.builtin.command:
    cmd: "{{ pyenv_path }}/shims/python3.9 -m venv --upgrade-deps {{ buildbot_venv }}"
    creates: "{{ buildbot_venv }}/bin/pip"
  become: true
  become_user: "{{ buildbot_user }}"

- name: Add PYENV_ROOT to /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^PYENV_ROOT='
    line: PYENV_ROOT="{{ pyenv_path }}"

- name: Install / upgrade buildbot worker
  ansible.builtin.command:
    cmd: "{{ buildbot_venv }}/bin/pip install --upgrade buildbot-worker"
  become: true
  become_user: "{{ buildbot_user }}"

- name: Check for buildbot.tac
  ansible.builtin.stat:
    path: "{{ buildbot_basedir }}/buildbot.tac"
  register: buildbot_tac

- name: Create buildbot.tac
  ansible.builtin.command:
    cmd: "{{ buildbot_venv }}/bin/buildbot-worker create-worker {{ buildbot_basedir }} buildbot-api.python.org:9020 {{ buildbot_name }} {{ buildbot_secret }}"
  become: true
  become_user: "{{ buildbot_user }}"
  when: not buildbot_tac.stat.exists

- name: Create buildbot directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: '0755'
  with_items:
    - "{{ buildbot_basedir }}"
    - "{{ buildbot_basedir }}/info"

- name: Reduce keepalive
  ansible.builtin.lineinfile:
    path: "{{ buildbot_basedir }}/buildbot.tac"
    regexp: "^keepalive ="
    line: "keepalive = 180"

- name: Create buildbot info/admin
  template:
    src: buildbot_admin.j2
    dest: "{{ buildbot_basedir }}/info/admin"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: '0644'

- name: Create buildbot info/host
  template:
    src: buildbot_host.j2
    dest: "{{ buildbot_basedir }}/info/host"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: '0644'

- name: Create systemd service
  template:
    src: buildbot.service.j2
    dest: "/etc/systemd/system/buildbot.service"
    owner: root
    group: root
    mode: '0755'

- name: Enable buildbot systemd service
  ansible.builtin.systemd:
    name: "buildbot"
    daemon_reload: true
    enabled: true

# cache emports as buildbot. embuilder clears outdated builds for us.
- name: Pre-build ports with embuilder
  ansible.builtin.command:
    cmd: "{{ emsdk_path }}/upstream/emscripten/embuilder build {{ item }}"
  with_items:
    - zlib
    - bzip2
    - sqlite3-mt
    - libc-mt
    - MINIMAL
  environment:
    EM_COMPILER_WRAPPER: ccache
  register: embuilder_output
  changed_when: '" generating " in embuilder_output.stderr'
  become: true
  become_user: "{{ buildbot_user }}"

- name: Pre-build ports with embuilder (PIC)
  ansible.builtin.command:
    cmd: "{{ emsdk_path }}/upstream/emscripten/embuilder build --pic {{ item }}"
  with_items:
    - zlib
    - bzip2
    - sqlite3
    - libc
    - MINIMAL_PIC
  environment:
    EM_COMPILER_WRAPPER: ccache
  register: embuilder_output
  changed_when: '" generating " in embuilder_output.stderr'
  become: true
  become_user: "{{ buildbot_user }}"

- name: Pre-build ports with embuilder (wasm64)
  ansible.builtin.command:
    cmd: "{{ emsdk_path }}/upstream/emscripten/embuilder build --wasm64 {{ item }}"
  with_items:
    - zlib
    - bzip2
    - sqlite3
    - libc
    - MINIMAL
  environment:
    EM_COMPILER_WRAPPER: ccache
  register: embuilder_output
  changed_when: '" generating " in embuilder_output.stderr'
  become: true
  become_user: "{{ buildbot_user }}"
